package s_gestion_usuarios.sop_corba;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from s_gestion_usuarios.idl
* martes 15 de febrero de 2022 10:52:48 AM COT
*/

public interface GestionPersonalOperations 
{
  void registrarPersonal (s_gestion_usuarios.sop_corba.GestionPersonalPackage.personalDTO objPersonal, org.omg.CORBA.BooleanHolder res);
  boolean consultarPersonal (int id, s_gestion_usuarios.sop_corba.GestionPersonalPackage.personalDTOHolder objPersonal);
  int abrirSesion (s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTO objCredencial);
} // interface GestionPersonalOperations
