package servidorDeNotificaciones.sop_corba;


/**
* servidorDeNotificaciones/sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* domingo 13 de febrero de 2022 06:56:49 PM COT
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
