package servidorDeNotificaciones.sop_corba;

/**
* servidorDeNotificaciones/sop_corba/GestionNotificacionesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* domingo 13 de febrero de 2022 06:56:49 PM COT
*/

public final class GestionNotificacionesHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorDeNotificaciones.sop_corba.GestionNotificaciones value = null;

  public GestionNotificacionesHolder ()
  {
  }

  public GestionNotificacionesHolder (servidorDeNotificaciones.sop_corba.GestionNotificaciones initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorDeNotificaciones.sop_corba.GestionNotificacionesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorDeNotificaciones.sop_corba.GestionNotificacionesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorDeNotificaciones.sop_corba.GestionNotificacionesHelper.type ();
  }

}
