package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/_GestionPacientesStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* domingo 13 de febrero de 2022 06:56:02 PM COT
*/

public class _GestionPacientesStub extends org.omg.CORBA.portable.ObjectImpl implements servidorDeAlertas.sop_corba.GestionPacientes
{

  public void registrarPaciente (servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTO objPacienteo, org.omg.CORBA.BooleanHolder resultado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarPaciente", true);
                servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHelper.write ($out, objPacienteo);
                $in = _invoke ($out);
                resultado.value = $in.read_boolean ();
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                registrarPaciente (objPacienteo, resultado        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarPaciente

  public boolean buscarPaciente (int numeroHabitacion, servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHolder objPacienteResultado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("buscarPaciente", true);
                $out.write_long (numeroHabitacion);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                objPacienteResultado.value = servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return buscarPaciente (numeroHabitacion, objPacienteResultado        );
            } finally {
                _releaseReply ($in);
            }
  } // buscarPaciente

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPacientes:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _GestionPacientesStub
