package servidorDeAlertas.sop_corba;


/**
* servidorDeAlertas/sop_corba/GestionPacientesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* domingo 13 de febrero de 2022 06:56:02 PM COT
*/

public interface GestionPacientesOperations 
{
  void registrarPaciente (servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTO objPacienteo, org.omg.CORBA.BooleanHolder resultado);
  boolean buscarPaciente (int numeroHabitacion, servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHolder objPacienteResultado);
} // interface GestionPacientesOperations
