package s_seguimiento_usuarios.sop_corba.GestionNotificacionesPackage;


/**
* s_seguimiento_usuarios/sop_corba/GestionNotificacionesPackage/NotificacionDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from s_seguimiento_usuarios.idl
* martes 15 de febrero de 2022 10:52:26 AM COT
*/

public final class NotificacionDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String nombreCompleto = null;
  public String ocupacion = null;

  public NotificacionDTO ()
  {
  } // ctor

  public NotificacionDTO (String _nombreCompleto, String _ocupacion)
  {
    nombreCompleto = _nombreCompleto;
    ocupacion = _ocupacion;
  } // ctor

  public String getNombreCompleto() {
    return this.nombreCompleto;
  }

  public void setNombreCompleto(String nombreCompleto) {
      this.nombreCompleto = nombreCompleto;
  }

  public String getOcupacion() {
      return this.ocupacion;
  }

  public void setOcupacion(String ocupacion) {
      this.ocupacion = ocupacion;
  }

} // class NotificacionDTO
