module sop_corba{
  
  interface GestionNotificaciones{
	struct NotificacionDTO {
		string nombreCompleto;
    	string ocupacion;
	};

    void notificarRegistro(in NotificacionDTO objNotificacion);
   };
 };

