package s_seguimiento_usuarios.sop_corba;


/**
* s_seguimiento_usuarios/sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from s_seguimiento_usuarios.idl
* martes 15 de febrero de 2022 10:52:26 AM COT
*/

public interface GestionNotificacionesOperations 
{
  void notificarRegistro (s_seguimiento_usuarios.sop_corba.GestionNotificacionesPackage.NotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
