package servidorDeAlertas.sop_corba.GestionPacientesPackage;

/**
* servidorDeAlertas/sop_corba/GestionPacientesPackage/pacienteDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* domingo 13 de febrero de 2022 06:56:02 PM COT
*/

public final class pacienteDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTO value = null;

  public pacienteDTOHolder ()
  {
  }

  public pacienteDTOHolder (servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return servidorDeAlertas.sop_corba.GestionPacientesPackage.pacienteDTOHelper.type ();
  }

}
