package s_seguimiento_usuarios.servidor;

import s_seguimiento_usuarios.sop_corba.*;
import s_seguimiento_usuarios.sop_corba.GestionNotificacionesPackage.*;
/**
* sop_corba/GesAnteproyectosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_ant.idl
* martes 9 de julio de 2019 06:45:59 AM COT
*/

public class GestionNotificacionesImpl implements GestionNotificacionesOperations {

	@Override
	public void notificarRegistro(NotificacionDTO objNotificacion) {
		System.out.println("**La persona:"+objNotificacion.getNombreCompleto()+", con ocupacion"+objNotificacion.getOcupacion()+"**");
        System.out.println("**esta autorizado para ingresar al sistema**");
		
	}
  

} 

