package s_gestion_usuarios.sop_corba.GestionPersonalPackage;

/**
* s_gestion_usuarios/sop_corba/GestionPersonalPackage/CredencialDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from s_gestion_usuarios.idl
* martes 15 de febrero de 2022 10:52:48 AM COT
*/

public final class CredencialDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTO value = null;

  public CredencialDTOHolder ()
  {
  }

  public CredencialDTOHolder (s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return s_gestion_usuarios.sop_corba.GestionPersonalPackage.CredencialDTOHelper.type ();
  }

}
