package s_gestion_usuarios.sop_corba.GestionPersonalPackage;


/**
* s_gestion_usuarios/sop_corba/GestionPersonalPackage/CredencialDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from s_gestion_usuarios.idl
* martes 15 de febrero de 2022 10:52:48 AM COT
*/

public final class CredencialDTO implements org.omg.CORBA.portable.IDLEntity
{
  public String usuario = null;
  public String clave = null;

  public CredencialDTO ()
  {
  } // ctor

  public CredencialDTO (String _usuario, String _clave)
  {
    usuario = _usuario;
    clave = _clave;
  } // ctor

  public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}


} // class CredencialDTO
