package servidorDeNotificaciones.servidor;

import servidorDeNotificaciones.sop_corba.*;
import servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.*;
/**
* sop_corba/GesAnteproyectosOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ges_ant.idl
* martes 9 de julio de 2019 06:45:59 AM COT
*/

public class GesNotificacionesImpl implements GestionNotificacionesOperations {
  public void notificarRegistro (servidorDeNotificaciones.sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion){
	if(objNotificacion.estado==1){
	  System.out.println("=========== NOTIFICACION ==================");
	  System.out.println("Se registro el paciente "+objNotificacion.nombre);
	  System.out.println("en la habitacion "+objNotificacion.numeroHabitacion+" EXITOSAMENTE");
	}
	else{
	  System.out.println("=========== NOTIFICACION ==================");
	  System.out.println("FALLO el registro del paciente "+objNotificacion.nombre);
	  System.out.println("en la habitacion "+objNotificacion.numeroHabitacion);
	}
  }
} 
